name: ${PROJECT_NAME:-your-project-name}

services:
    wordpress:
        image: wordpress:${WORDPRESS_VERSION:-php8.3-apache}
        container_name: ${CONTAINER_PREFIX:-wordpress}-app
        restart: always
        ports:
            - ${WEB_PORT:-6969}:80
        environment:
            - WORDPRESS_DB_HOST=wordpressdb
            - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
            - WORDPRESS_DB_USER=${DB_USER:-wordpress}
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-examplepass}
        depends_on:
            wordpressdb:
                condition: service_healthy
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - wordpress_network

    wpcli:
        image: wordpress:cli-${WORDPRESS_CLI_VERSION:-php8.3}
        container_name: ${CONTAINER_PREFIX:-wordpress}-wpcli
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=wordpressdb
            - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
            - WORDPRESS_DB_USER=${DB_USER:-wordpress}
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-examplepass}
            - WP_CLI_CACHE_DIR=/var/www/html/.wp-cli-cache
            - WP_CLI_ALLOW_ROOT=1
        depends_on:
            wordpressdb:
                condition: service_healthy
            wordpress:
                condition: service_started
        networks:
            - wordpress_network
        profiles:
            - cli

    wordpressdb:
        image: mysql:${MYSQL_VERSION:-8.4.2}
        container_name: ${CONTAINER_PREFIX:-wordpress}-db
        restart: always
        ports:
            - ${MYSQL_PORT:-3306}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=${DB_USER:-wordpress}
            - MYSQL_PASSWORD=${DB_PASSWORD:-examplepass}
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 20s
            retries: 10
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - wordpress_network

    phpmyadmin:
        image: phpmyadmin:${PHPMYADMIN_VERSION:-5.2-apache}
        container_name: ${CONTAINER_PREFIX:-wordpress}-phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=wordpressdb
        networks:
            - wordpress_network

    mailpit:
        image: axllent/mailpit:${MAILPIT_VERSION:-latest}
        container_name: ${CONTAINER_PREFIX:-wordpress}-mailpit
        restart: always
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - wordpress_network

networks:
    wordpress_network:
